App\Entity\Location:
  properties:
    latitude:
      - Range:
          min: -90
          max: 90
    longitude:
      - Range:
          min: -90
          max: 90

App\Entity\Forecast:
  properties:
    temperature:
      - Range:
          min: -50
          max: 100
    pressure:
      - GreaterThanOrEqual: 900
    humidity:
      - Range:
          min: 0
          max: 100
    windSpeed:
      - PositiveOrZero: ~
    windDeg:
      - PositiveOrZero: ~
    cloudiness:
      - Range:
          min: 0
          max: 100